### ISSUE TITLE
How do you use  DbgMemFindBaseAddr(duint addr, duint* size) ??

### ISSUE THREAD

**Issue by Th4nat0s** [x64dbg/x64dbgpy#14]
Hello 

I try to get the base address and the len of a allocated segment for a given offset. 

I don't known how to create the duint pointer required in second argument in python. 
I have try to use Ctype.

```
            address = 0x400000
            slen = 0
            slen_p = c_void_p(slen)
            print DbgMemFindBaseAddr(address, slen_p)
            print slen
```
        
But 

```
Traceback (most recent call last):
  File "C:\PROGRA~1\odbg\release\x32\plugins\x64dbgpy\x64dbgpy\__breakpoints.py", line 42, in __breakpoint_function
    **{key: value for key, value in kwargs.iteritems() if key in arg_keys}
  File "C:\Users\azerty\Desktop\UNPACK~1.PY", line 58, in bpcallback
    print DbgMemFindBaseAddr(address, slen_p)
TypeError: in method 'DbgMemFindBaseAddr', argument 2 of type 'duint *'
```

Anyone knows ?

**Comment by mrfearless** [comment]
2nd parameter of DbgMemFindBaseAddr is a pointer to a variable to store the returned size.

duint is a long (dword) in 32bits, and long long (qword) in 64bits - so its a macro / abstraction to handle the proper size for x32dbg (x86) or x64dbg (x64), depending on which it was compiled for.

**Comment by Th4nat0s** [comment]
That's what i had understand from the code. but how to use that. I have try to create a pointer to my int. (Python 2/32bits)

**Comment by mrexodia** [comment]
You can use the scriptapi. Should be somewhere in the Memory module.

Please note that currently the api is a complete mess so it's kind of hard
to do things...

**Comment by Th4nat0s** [comment]
Well :) bit out of scope, but if it's work... Any example somewhere

**Comment by mrexodia** [comment]
see https://github.com/x64dbg/x64dbgpy/blob/v25/swig/x64dbgpy/pluginsdk/_scriptapi/memory.py#L26

**Comment by Th4nat0s** [comment]
def get_segment(address):
    base = GetBase(address, False, False)
    slen = GetSize(base, False, False)
    return (base,slen)

Work's Thank's mrexodia !

**Comment by mrexodia** [comment]
@Th4nat0s could you come in the chat (irc/telegram/gitter) or email me at mrexodia [at] x64dbg.com

We are looking into developing a new api and some of your input as a user would be nice.
