### ISSUE TITLE
Wrong values in the class Flag

### ISSUE THREAD

**Issue by yennlh** [x64dbg/x64dbgpy#16]
Hi,

I just tried to use the class x64dbgpy.Flag and realized that the values of flags are always incorrect. 
Could you please resolve this issues?

Sincerely,
Yen

**Comment by mrexodia** [comment]
Could you give an example script that shows this problem please?

**Comment by mrexodia** [comment]
Okay was a bug in x64dbg, should be fixed now.

**Comment by yennlh** [comment]
Excuse me! Was it fixed in the last snapshot on https://ci.appveyor.com/project/mrexodia/x64dbg-python/build/artifacts ? I downloaded this snapshot and integrate it into the last snapshot of x64dbg. Then, I tried to execute the following script, but I got the wrong values which are different from the values displayed on x64dbg GUI.

> from x64dbgpy import *
> 
> print Flag.AF
> print Flag.ZF
> print Flag.PF

**Comment by mrexodia** [comment]
I'll try again, it should work in theory with the latest x64dbg from releases.x64dbg.com

**Comment by mrexodia** [comment]
Just tested, works as expected...

**Comment by yennlh** [comment]
Could you please let me know which release of x64dbg did you use for testing? This is what I got when I executed the script on snapshot_2017-08-11_05-43. 

![screenshot](https://user-images.githubusercontent.com/12070458/29301704-14df9f5c-81b9-11e7-8acf-ecd4e05ef700.png)

```
from x64dbgpy import *

print 'ZF = ', Flag.ZF
print 'PF = ', Flag.PF
print 'AF = ', Flag.AF
print 'OF = ', Flag.OF
print 'SF = ', Flag.SF
print 'DF = ', Flag.DF
print 'CF = ', Flag.CF
print 'TF = ', Flag.TF
print 'IF = ', Flag.IF
```

**Comment by mrexodia** [comment]
The one from the time I said the issue was fixed. 14 of August

**Comment by yennlh** [comment]
Great! Eventually, it worked for me with the last release snapshot_2017-08-14_16-50. I didn't find it out because I downloaded from http://snapshots.x64dbg.com/, which is referred by the homepage of x64dbg. Thank you very much for your help. 😄

**Comment by mrexodia** [comment]
Yeah those snapshots should update daily to not spam the sourceforge servers too much...

**Comment by yennlh** [comment]
Btw, could you please let me know how to interact with XMM registers via x64dbgpy?

**Comment by mrexodia** [comment]
You cannot right now.
