### ISSUE TITLE
no memory r/w access breakpoint api

### ISSUE THREAD

**Issue by kismp123** [x64dbg/x64dbgpy#19]
Hi!
first of all, I want to say thank you.
it's really helpful for unpacking programs. ( unpacking really fun !)

is exist memory r/w access breakpoint api? 
memory r/w access breakpoint means breakpoint on one section.

```
SCRIPT_EXPORT bool SetBreakpoint(duint address);
SCRIPT_EXPORT bool DeleteBreakpoint(duint address);
SCRIPT_EXPORT bool DisableBreakpoint(duint address);
SCRIPT_EXPORT bool SetHardwareBreakpoint(duint address, HardwareType type = HardwareExecute);
SCRIPT_EXPORT bool DeleteHardwareBreakpoint(duint address);
```

SetBreakpoint api looks like software breakpoint.
and SetHardwareBreakpoint is Hardwarebreakpoint.

if you add script api about r/w access, I'm really thankful
Best regards.

**Comment by mrexodia** [comment]
You can use the [SetMemoryBPX](http://help.x64dbg.com/en/latest/commands/breakpoint-control/SetMemoryBPX.html) command for now.

**Comment by kismp123** [comment]
Thank you! 
I've noticed document now !

**Comment by kismp123** [comment]
Thank you!
I've noticed document now !
but how can I use SetMemoryBPX?
NameError : name "SetMemoryBPX" is not defined :(

**Comment by mrexodia** [comment]
You have to execute it as an x64dbg command so `DbgCmdExecDirect("SetMemoryBPX ...")`

**Comment by kismp123** [comment]
Thank you!

**Comment by kismp123** [comment]
sorry again. I couldn't found DbgCmdExecDirect function.

I've found in bridgemain.h
```
BRIDGE_IMPEXP bool DbgCmdExecDirect(const char* cmd);
```

but I couldn't found python function
```
Help on module x64dbgpy.pluginsdk.bridgemain in x64dbgpy.pluginsdk:

NAME
    x64dbgpy.pluginsdk.bridgemain

FILE
    c:\x64dbg\release\x32\plugins\x64dbgpy\x64dbgpy\pluginsdk\bridgemain.py

FUNCTIONS
    DbgIsDebugging()
    
    GuiGetLineWindow(title='')
    
    GuiGetWindowHandle()
    
    GuiLogClear()
    
    GuiUpdateAllViews()

DATA
    GUI_MAX_LINE_SIZE = 65536
```

I've typed command "x64dbgpy.pluginsdk.bridgemain.DbgCmdExecDirect" 
couldn't found.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'DbgCmdExecDirect'
```

or is exists to disassemble address? and is exists to get instruction size ?
Thank you

**Comment by techbliss** [comment]
@kismp123  

`DbgCmdExecDirect("")` 
Uses the command system from c++ to set the memory breakpoint with the command "SetMemoryBPX", that is why you wont find it in the python API.

**Comment by mrexodia** [comment]
It should be in the python api somewhere, I used it multiple times...

**Comment by mrexodia** [comment]
@kismp123 See https://github.com/x64dbg/Scripts/blob/master/UpxUnpacker.py for an example of `DbgCmdExecDirect`

**Comment by kismp123** [comment]
Thank you again! 👍
