### ISSUE TITLE
Unable to change x64dbg.ini Python home

### ISSUE THREAD

**Issue by wangray** [x64dbg/x64dbgpy#23]
I try to point the pythonhome to another Python install folder, but my changes are overridden on next x64dbg restart. 

RIght now, I'm being forced to install python in `C:\Python27`?

**Comment by mrexodia** [comment]
It shouldn't happen. See [findX64dbgPythonHome](https://github.com/x64dbg/x64dbgpy/blob/v25/py.cpp#L629). If the python home you specified passed `isValidPythonHome` it should not be reset...

**Comment by wangray** [comment]
Hm... I tried it a few more times and it worked. Dunno what happened before
