### ISSUE TITLE
Question: Can x64dbgpy do BP Hooks?

### ISSUE THREAD

**Issue by deeso** [x64dbg/x64dbgpy#24]
ImmunityDbg has BpHooks, and I was wondering if your API has anything like this for x64dbg?

**Comment by mrexodia** [comment]
Probably yes

**Comment by mrexodia** [comment]
Try it

**Comment by deeso** [comment]
Can you provide a pointer?  I don't see any code in your script API that lets me register a Callback when the BP is hit.  Thanks.
