### ISSUE TITLE
Cannot use the "recent" version. ImportError

### ISSUE THREAD

**Issue by Th4nat0s** [x64dbg/x64dbgpy#30]
Hello, I use the python integration since while now and I had upgraded to the last one provided by 
I cant use it anymore...

```
from _x64dbg import *
ImportError: No module named _x64dbg

```
Did the import syntax changed ? If I revert the plugin folder to the old one , it works well.
Both where fetched here https://ci.appveyor.com/project/mrexodia/x64dbg-python/build/artifacts

The NOT working one from https://github.com/x64dbg/x64dbgpy/tree/v25
4b1c14f36d14c15417885c76273212e3 compiled Tue Jul 10 22:47:15 2018

The working one
32d566001c71295ed0609691ca26dd86 compiled Tue Apr  4 02:33:28 2017

**Comment by katoon123** [comment]
You're such a fuckin' ho, I love it
You're such a fuckin' ho, I love it
You're such a fuckin' ho, I love it
Your boyfriend is a dork, McLovin ooh, ooh
I just pulled up in a Ghost
Fucked that bitch up out in London
Then I fucked up on her cousin
Or her sister, I don't know nothin'
And my niggas gettin' ignorant
Like a lighter, bitch, we ignant
All this water on my neck
Look like I fell when I went fishin'
So much diamonds on my bust down
Ooh, fuck, what's the time?
Me and Smokepurpp sippin' drank
Ooh, fuck, she take lines

Kind Regards

**Comment by Th4nat0s** [comment]
Quite boring theses stupid hack :) ...  @katoon123 Unsuscribe ! :) ...

Anyway... It is not related to the x64dbgpy.dp32 file. I still dig into... I could swap this file without any issue.

**Comment by SabedMako** [comment]
De quoi vous voulez dire?

Le 20 oct. 2018 2:39 PM, Thanat0s <notifications@github.com> a écrit :

Quite boring theses stupid hack :) ... @katoon123<https://github.com/katoon123> Unsuscribe ! :) ...

Anyway... It is not related to the x64dbgpy.dp32 file. I still dig into...

**Comment by Th4nat0s** [comment]
Ok after a small dichotomous game, the problem is related to two files.

in \x32\plugins\x64dbgpy\x64dbgpy\pluginsdk with x64dbg.py and _x64dbg.pyd

working one (_x64dbg.pyd) 
compiled Tue Apr  4 02:33:47 2017
1916db42c3489d17b383fbe1712a2e57

**Comment by Th4nat0s** [comment]
Ok seems that now i should do import by using **x64dbgpy** and not **_x64dbg**

**Comment by Th4nat0s** [comment]
Some changes so...


from x64dbgpy.pluginsdk import *
x64dbg.DbgCmdExecDirect("mycommand")

**Comment by Dagobert-** [comment]
What up cuh's?

**Comment by SabedMako** [comment]
Ça va je te remercie, et toi?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by samsta458** [comment]
I'm stealing all of the information. Thanks for the data
