### ISSUE TITLE
Unable to load x64dbgpy plugin in the latest version of x32dbg

### ISSUE THREAD

**Issue by ChangUk** [x64dbg/x64dbgpy#34]
It is unable to load x64dbgpy plugin in the latest version of x32dbg, while it is successfully loaded in x64dbg(64-bit). I'm using "Mar 10 2019" version of x64dbg and Anaconda2(both 32bit and 64bit). The log message is as follows:

```
[PLUGIN]Failed to load plugin: x64dbgpy.dp32
[PLUGIN, xAnalyzer] Command "xanal" registered!
[PLUGIN, xAnalyzer] Command "xanalremove" registered!
[PLUGIN] xAnalyzer v2 Loaded!
```

As shown above, another plugin (xAnalyzer in this case) is successfully loaded. Please check it out.

**Comment by ChangUk** [comment]
Solved. It was caused by incorrect system environment variables...

**Comment by BackTrackCRoot** [comment]
I have same problem, can you tell me how you solved this problem? Thanks for lot.

**Comment by Joshehutch** [comment]
No, get your own answers.
