### ISSUE TITLE
Appveyor snapshots expired

### ISSUE THREAD

**Issue by ngo** [x64dbg/x64dbgpy#35]
The appveyor snapshots are stored only 6 months, so they've recently expired and currently there is no way to download a recent compiled version of x64dbgpy.

**Comment by mrexodia** [comment]
I have triggered a new build.

**Comment by ngo** [comment]
Yeah, and the build triggered #36

**Comment by marselSh** [comment]
Test

пт, 19 июля 2019 г., 15:00 ngo <notifications@github.com>:
