### ISSUE TITLE
-outputtuple is removed in swig 4.0.0.

### ISSUE THREAD

**Issue by ngo** [x64dbg/x64dbgpy#36]
Currently this option is used here:
https://github.com/x64dbg/x64dbgpy/blob/0cba3acd66ca4288b2ea0abd447edc6121a8a245/swig/setup.py#L33

As per https://fossies.org/linux/privat/swig-4.0.0.tar.gz/swig-4.0.0/CHANGES.current (search for #1340), this option was removed from swig 4.0.0.

What is the purpose of including this option here?

**Comment by ngo** [comment]
@realgam3, you seem to be the author of the main codebase here. Do you remember any specific reason for using -outputtuple switch for swig? What would be the best way to change code so that it's safe to remove?

**Comment by techbliss** [comment]
only thing i can find on the subject is https://github.com/swig/swig/commit/0a9b36d3beb0055ad685583fd8d91c715d8e0d7e

**Comment by ngo** [comment]
@techbliss , the commit you mentioned disables support for this option in SWIG, but does not shed any light on whether x64dbgpy actually uses the behavior provided by -outputtuple. From my very limited testing removing this option does not impact any exisiting functions of x64dbgpy, but you can never be sure...

**Comment by techbliss** [comment]
Yeah you never know, just wierd that the auther of swig do not know either.

**Comment by mrexodia** [comment]
This isn't really solved, but I just fixed swig to an older version. Eventually the plan is to do manual bindings with pybind11 anyway because swig is too fugly.
