### ISSUE TITLE
Stop shipping binaries in the repo and purge them from commits history

### ISSUE THREAD

**Issue by KOLANICH** [x64dbg/x64dbgpy#45]

**Comment by mrexodia** [comment]
Which binaries would that be?

**Comment by KOLANICH** [comment]
All the files that are binary. git doesn't handle them efficiently, they cause the repo size grow a lot (there exist repos of libraries over a GiB in size because their maintainers considers rewriting history and/or storing binary files in other places as inacceptable), so they should be removed from history too. Especially exes available in other places - instead instructions how to get them should be provided and maybe a script doing it.

**Comment by mrexodia** [comment]
There are no binaries that are irrelevant. Git is not meant for frequent binary updates, but the binaries here are not updated frequently and it’s often not possible to reproduce the stuff without binaries.

**Comment by KOLANICH** [comment]
Then GIT LFS should be used for them.

**Comment by mrexodia** [comment]
No. I’m confused about your issues. You seem to open random issue related
to best practices, without actually trying to understand what’s going on in
this project. The binaries here are a total of maybe 200kb. Nobody in their
right mind should be using git lfs for that.

**Comment by habaniko** [comment]
Please unsubscribe me. Why should be on git hub to be able to stop your
emails?
Please take me off your list!
Thanks

Duncan Ogilvie <notifications@github.com> ezt írta (időpont: 2019. dec. 5.,
Csü 8:04):

**Comment by habaniko** [comment]
Please unsubscribe me. Why should be on git hub to be able to stop your
emails?
Please take me off your list!
Thanks

Duncan Ogilvie <notifications@github.com> ezt írta (időpont: 2019. dec. 5.,
Csü 20:31):

> No. I’m confused about your issues. You seem to open random issue related
> to best practices, without actually trying to understand what’s going on in
> this project. The binaries here are a total of maybe 200kb. Nobody in their
> right mind should be using git lfs for that.
>
