### ISSUE TITLE
Is there a API to get "FileOffset" of RVA ?

### ISSUE THREAD

**Issue by nevinhappy** [x64dbg/x64dbgpy#50]
Just like the command : mod.offset(addr) to get the fileoffset , But I can't find any function can do this. Anyone know how to make this ?

**Comment by mrexodia** [comment]
You can call DbgValFromString and evaluate any expression you want

**Comment by nevinhappy** [comment]
Thand you for your quick support . This function is powerful. 
------------------------------------------------------------------------
```python
     x64dbg.DbgValFromString('mod.offset(0x%X)' % find_ret)
```
Note: the arg of mod.offset should be hex format .
