### ISSUE TITLE
Downloading latest release (Appveyor artifacts automatically removed after 1 month)

### ISSUE THREAD

**Issue by Downloading69** [x64dbg/x64dbgpy#62]
Hello there,

I'm trying to download the latest builds, but it seems appveyor removes them after 1 month...

Kind regards,

Me

**Comment by saturn4er** [comment]
@Downloading69  just build one in fork https://github.com/saturn4er/x64dbgpy/releases/tag/v24

**Comment by mrexodia** [comment]
Don’t do that, there could be anything in that fork.

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbgpy/releases/tag/b275005

**Comment by mrexodia** [comment]
Thanks btw @saturn4er, but I think it's better to keep binaries in the official repo.

**Comment by saturn4er** [comment]
@mrexodia sure, but I'm not an owner

**Comment by Downloading69** [comment]
Thank you all!
